"use strict";

/* Downloads the latin subset of Plus Jakarta Sans (the single typeface used by
   Troolify) from Google Fonts and writes a local @font-face stylesheet so the
   pages no longer depend on fonts.googleapis.com / fonts.gstatic.com.

   Run:  node troolify-gen/setup-fonts.js
   Output: assets/fonts/jakarta-{wght}.woff2 + assets/css/jakarta.min.css
*/
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const OUT = (p) => path.join(ROOT, "assets", p);
const CSS2 = "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800;900&display=swap";
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

async function main() {
  const css = await fetch(CSS2, { headers: { "User-Agent": UA } }).then((r) => r.text());
  const blockRe = /\/\* latin \*\/\s*@font-face\s*\{([^}]*)\}/g;
  let m;
  const faces = [];
  while ((m = blockRe.exec(css))) {
    const body = m[1];
    const wght = /font-weight:\s*(\d+)/.exec(body);
    const url = /url\((https:[^)]+\.woff2)\)/.exec(body);
    if (wght && url) faces.push({ wght: wght[1], url: url[1] });
  }
  if (!faces.length) throw new Error("No latin @font-face blocks parsed from Google Fonts CSS");
  const seen = new Set();
  const picked = faces.filter((f) => !seen.has(f.wght) && seen.add(f.wght));

  fs.mkdirSync(OUT("fonts"), { recursive: true });
  const cssOut = ["/* Auto-generated by troolify-gen/setup-fonts.js - do not edit */"];
  for (const f of picked) {
    const buf = Buffer.from(await (await fetch(f.url)).arrayBuffer());
    const file = `jakarta-${f.wght}.woff2`;
    fs.writeFileSync(OUT(`fonts/${file}`), buf);
    cssOut.push(
      `@font-face{font-family:"Plus Jakarta Sans";font-style:normal;font-weight:${f.wght};font-display:swap;src:url(../fonts/${file}) format("woff2");unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}`
    );
    console.log(`downloaded jakarta-${f.wght}.woff2 (${(buf.length / 1024).toFixed(0)} KB)`);
  }
  fs.writeFileSync(OUT("css/jakarta.min.css"), cssOut.join("\n") + "\n", "utf8");
  console.log("jakarta.min.css written");
}

main().catch((e) => { console.error(e); process.exit(1); });